import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// app/(public)/layout.tsx
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

    <div className="flex flex-col min-h-screen">
      {/* Header */}
      <header className="bg-white shadow-md px-6 py-4">
        <div className="flex items-center justify-between max-w-7xl mx-auto">
          <Link href="/" className="text-xl font-bold text-primary">
            WebiSalesPro
          </Link>
          <nav className="space-x-6 text-sm text-muted-foreground">
            {/* <Link href="/login">Login</Link>
            <Link href="/register">Sign Up</Link> */}
          </nav>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 max-w-7xl mx-auto px-4 py-6">
        {children}
      </main>

      {/* Footer */}
      <footer className="bg-gray-50 border-t mt-6">
        <div className="max-w-7xl mx-auto py-6 px-4 text-sm text-muted-foreground flex justify-between items-center">
          <span>© {new Date().getFullYear()} WebiSalesPro. All rights reserved.</span>
          <div className="space-x-4">
            <Link href="/privacy">Privacy</Link>
            <Link href="/terms">Terms</Link>
            <Link href="/contact">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
    </body>
    </html>
  )
}
